# Generated by Django 4.0.5 on 2022-07-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('facebook_link', models.URLField(max_length=300)),
                ('twitter_link', models.URLField(max_length=300)),
                ('google_plus_link', models.URLField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
